// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class seedUsers2ndtime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedUsers2ndtime));
        
        string IMigrationMetadata.Id
        {
            get { return "201806090454065_seedUsers2ndtime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
